[package]
name = "python2rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
cpython = "0.7.1"
eyre = "0.6.12"
maplit = "1.0.2"
pyo3 = "0.20.3"
thiserror = "1.0.58"
